CategoryType.delete_all
CategoryType.create(id: 0, name: "location")
CategoryType.create(id: 2, name: "operator")
CategoryType.create(id: 3, name: "legal_or_person")
CategoryType.create(id: 4, name: "standard_service")
CategoryType.create(id: 5, name: "base_service")
CategoryType.create(id: 6, name: "service_direction")
CategoryType.create(id: 7, name: "param_value_type")
CategoryType.create(id: 8, name: "param_source")
CategoryType.create(id: 9, name: "unit")
CategoryType.create(id: 14, name: "comparison_operator")
CategoryType.create(id: 15, name: "param_source_type")
CategoryType.create(id: 16, name: "field_display_type")
CategoryType.create(id: 17, name: "value_choose_option")
CategoryType.create(id: 18, name: "service_category_type")
CategoryType.create(id: 19, name: "operator_type")
CategoryType.create(id: 20, name: "user_service_status")
CategoryType.create(id: 21, name: "relation types")
CategoryType.create(id: 22, name: "phone usage patterns")
CategoryType.create(id: 23, name: "priority_type")
CategoryType.create(id: 24, name: "priority_relation")
CategoryType.create(id: 25, name: "general_priority")
CategoryType.create(id: 26, name: "tarif_class_general_service_categories")
CategoryType.create(id: 27, name: "customer_info_type")
CategoryType.create(id: 28, name: "customer_demand_type")
CategoryType.create(id: 29, name: "customer_demand_status")
CategoryType.create(id: 30, name: "content_type")
CategoryType.create(id: 31, name: "content_status")
CategoryType.create(id: 32, name: "content_key_rouming")
CategoryType.create(id: 33, name: "content_key_service")
CategoryType.create(id: 34, name: "content_key_destination")
CategoryType.create(id: 35, name: "content_key_usage_intensity")

CategoryLevel.delete_all
CategoryLevel.create(id: 0,type_id: 0, level: 0, name: "world")
CategoryLevel.create(id: 1,type_id: 0, level: 1, name: "continent")
CategoryLevel.create(id: 2,type_id: 0, level: 2, name: "country")
CategoryLevel.create(id: 3,type_id: 0, level: 3, name: "region")
CategoryLevel.create(id: 20,type_id: 9, level: 0, name: "unit type")
CategoryLevel.create(id: 21,type_id: 9, level: 1, name: "unit")

Customer::Category.delete_all
Customer::Category.create(id: 1, type_id: 27, name: "general_info")
Customer::Category.create(id: 2, type_id: 27, name: "cash_info")
Customer::Category.create(id: 3, type_id: 27, name: "service_used_info")
Customer::Category.create(id: 4, type_id: 27, name: "calls_generation_params")
Customer::Category.create(id: 5, type_id: 27, name: "calls_details_params")
Customer::Category.create(id: 6, type_id: 27, name: "calls_parsing_params")
Customer::Category.create(id: 7, type_id: 27, name: "tarif_optimization_params")
Customer::Category.create(id: 8, type_id: 27, name: "service_choices")
Customer::Category.create(id: 9, type_id: 27, name: "services_select")
Customer::Category.create(id: 10, type_id: 27, name: "service_categories_select")
Customer::Category.create(id: 11, type_id: 27, name: "tarif_optimization_final_results")
Customer::Category.create(id: 12, type_id: 27, name: "tarif_optimization_minor_results")
Customer::Category.create(id: 13, type_id: 27, name: "tarif_optimization_process_status")

Category.delete_all
Category.create(id: 1, type_id: 3, level_id: nil, parent_id: nil, name: "Для юридических лиц")
Category.create(id: 2, type_id: 3, level_id: nil, parent_id: nil, name: "Для физических лиц")

Category.create(id: 40, type_id: 4, level_id: nil, parent_id: nil, name: "Тариф")
Category.create(id: 41, type_id: 4, level_id: nil, parent_id: nil, name: "Общая услуга")
Category.create(id: 42, type_id: 4, level_id: nil, parent_id: nil, name: "Тарифная опция")
Category.create(id: 43, type_id: 4, level_id: nil, parent_id: nil, name: "Опция тарифа")
Category.create(id: 44, type_id: 4, level_id: nil, parent_id: nil, name: "Тестовые")
Category.create(id: 45, type_id: 4, level_id: nil, parent_id: nil, name: "Для специальных задач")

Category.create(id: _calls, type_id: 5, level_id: nil, parent_id: nil, name: "Звонок")
Category.create(id: _sms, type_id: 5, level_id: nil, parent_id: nil, name: "СМС")
Category.create(id: _mms, type_id: 5, level_id: nil, parent_id: nil, name: "ММС")
Category.create(id: _wap, type_id: 5, level_id: nil, parent_id: nil, name: "wap")
Category.create(id: _2g, type_id: 5, level_id: nil, parent_id: nil, name: "2G")
Category.create(id: _3g, type_id: 5, level_id: nil, parent_id: nil, name: "3G")
Category.create(id: _4g, type_id: 5, level_id: nil, parent_id: nil, name: "4G")
Category.create(id: _cdma, type_id: 5, level_id: nil, parent_id: nil, name: "CDMA")
Category.create(id: _wifi, type_id: 5, level_id: nil, parent_id: nil, name: "WiFi")
Category.create(id: _periodic, type_id: 5, level_id: nil, parent_id: nil, name: "periodic")
Category.create(id: _one_time, type_id: 5, level_id: nil, parent_id: nil, name: "one_time")

Category.create(id: 70, type_id: 6, level_id: nil, parent_id: nil, name: "Исходящий")
Category.create(id: 71, type_id: 6, level_id: nil, parent_id: nil, name: "Входящий")
Category.create(id: 72, type_id: 6, level_id: nil, parent_id: nil, name: "Без категории")

Category.create(id: 3, type_id: 7, level_id: nil, parent_id: nil, name: "boolean")
Category.create(id: 4, type_id: 7, level_id: nil, parent_id: nil, name: "integer")
Category.create(id: 5, type_id: 7, level_id: nil, parent_id: nil, name: "string")
Category.create(id: 6, type_id: 7, level_id: nil, parent_id: nil, name: "text")
Category.create(id: 7, type_id: 7, level_id: nil, parent_id: nil, name: "decimal")
Category.create(id: 8, type_id: 7, level_id: nil, parent_id: nil, name: "list")
Category.create(id: 9, type_id: 7, level_id: nil, parent_id: nil, name: "reference")
Category.create(id: 10, type_id: 7, level_id: nil, parent_id: nil, name: "datetime")
Category.create(id: 11, type_id: 7, level_id: nil, parent_id: nil, name: "json")
Category.create(id: 12, type_id: 7, level_id: nil, parent_id: nil, name: "array")

Category.create(id: 15, type_id: 8, level_id: nil, parent_id: nil, name: "User phones")
Category.create(id: 16, type_id: 8, level_id: nil, parent_id: nil, name: "User service description")
Category.create(id: 17, type_id: 8, level_id: nil, parent_id: nil, name: "Operator service description")
Category.create(id: 18, type_id: 8, level_id: nil, parent_id: nil, name: "Used service description")
Category.create(id: 19, type_id: 8, level_id: nil, parent_id: nil, name: "Tarif service description")

Category.create(id: 75,type_id: 9, level_id: 20, parent_id: nil, name: "characteristic_unit")
Category.create(id: 76,type_id: 9, level_id: 20, parent_id: nil, name: "trafic_unit")
Category.create(id: 77,type_id: 9, level_id: 20, parent_id: nil, name: "cost_unit")
Category.create(id: 78,type_id: 9, level_id: 20, parent_id: nil, name: "date_time_unit")
Category.create(id: 79,type_id: 9, level_id: 20, parent_id: nil, name: "trafic_speed_unit")

Category.create(id: 80, type_id: 9, level_id: 21, parent_id: 76, name: "Байт")
Category.create(id: 81, type_id: 9, level_id: 21, parent_id: 76, name: "Кб")
Category.create(id: 82, type_id: 9, level_id: 21, parent_id: 76, name: "Мб")
Category.create(id: 83, type_id: 9, level_id: 21, parent_id: 76, name: "Гб")

Category.create(id: 90, type_id: 9, level_id: 21, parent_id: 77, name: "RUR")
Category.create(id: 91, type_id: 9, level_id: 21, parent_id: 77, name: "USD")
Category.create(id: 92, type_id: 9, level_id: 21, parent_id: 77, name: "EUR")
Category.create(id: 93, type_id: 9, level_id: 21, parent_id: 77, name: "Grivna")
Category.create(id: 94, type_id: 9, level_id: 21, parent_id: 77, name: "GBP")

Category.create(id: 95, type_id: 9, level_id: 21, parent_id: 78, name: "секунда")
Category.create(id: 96, type_id: 9, level_id: 21, parent_id: 78, name: "минута")
Category.create(id: 97, type_id: 9, level_id: 21, parent_id: 78, name: "час")
Category.create(id: 98, type_id: 9, level_id: 21, parent_id: 78, name: "сутки")
Category.create(id: 99, type_id: 9, level_id: 21, parent_id: 78, name: "неделя")
Category.create(id: 100, type_id: 9, level_id: 21, parent_id: 78, name: "месяц")
Category.create(id: 101, type_id: 9, level_id: 21, parent_id: 78, name: "год")

Category.create(id: 110, type_id: 9, level_id: 21, parent_id: 79, name: "Кб/с")
Category.create(id: 111, type_id: 9, level_id: 21, parent_id: 79, name: "Мб/с")
Category.create(id: 112, type_id: 9, level_id: 21, parent_id: 79, name: "Гб/с")

Category.create(id: 115, type_id: 9, level_id: 21, parent_id: 75, name: "шт.")

Category.create(id: 120, type_id: 14, level_id: nil, parent_id: nil, name: "=")
Category.create(id: 121, type_id: 14, level_id: nil, parent_id: nil, name: "!=")
Category.create(id: 122, type_id: 14, level_id: nil, parent_id: nil, name: "<")
Category.create(id: 123, type_id: 14, level_id: nil, parent_id: nil, name: "<=")
Category.create(id: 124, type_id: 14, level_id: nil, parent_id: nil, name: ">")
Category.create(id: 125, type_id: 14, level_id: nil, parent_id: nil, name: "=>")
Category.create(id: 126, type_id: 14, level_id: nil, parent_id: nil, name: "in")
Category.create(id: 127, type_id: 14, level_id: nil, parent_id: nil, name: "not_in")

Category.create(id: 130, type_id: 15, level_id: nil, parent_id: nil, name: "original")
Category.create(id: 131, type_id: 15, level_id: nil, parent_id: nil, name: "intermediate")
Category.create(id: 132, type_id: 15, level_id: nil, parent_id: nil, name: "input")

Category.create(id: 135, type_id: 16, level_id: nil, parent_id: nil, name: "value")
Category.create(id: 136, type_id: 16, level_id: nil, parent_id: nil, name: "list")
Category.create(id: 137, type_id: 16, level_id: nil, parent_id: nil, name: "table")
Category.create(id: 138, type_id: 16, level_id: nil, parent_id: nil, name: "string")
Category.create(id: 139, type_id: 16, level_id: nil, parent_id: nil, name: "query")

Category.create(id: 150, type_id: 17, level_id: nil, parent_id: nil, name: "field")
Category.create(id: 151, type_id: 17, level_id: nil, parent_id: nil, name: "single_value")
Category.create(id: 152, type_id: 17, level_id: nil, parent_id: nil, name: "multiple_value")
Category.create(id: 153, type_id: 17, level_id: nil, parent_id: nil, name: "value_param_is_criterium_param")

Category.create(id: 160, type_id: 18, level_id: nil, parent_id: nil, name: "common")
Category.create(id: 161, type_id: 18, level_id: nil, parent_id: nil, name: "specific")

Category.create(id: 170, type_id: 19, level_id: nil, parent_id: nil, name: "mobile")
Category.create(id: 171, type_id: 19, level_id: nil, parent_id: nil, name: "fixed line")

Category.create(id: 175, type_id: 20, level_id: nil, parent_id: nil, name: "subscribed")
Category.create(id: 176, type_id: 20, level_id: nil, parent_id: nil, name: "unsubscribed")
Category.create(id: 177, type_id: 20, level_id: nil, parent_id: nil, name: "expired")

Category.create(id: _operator_home_regions, type_id: 21, level_id: nil, parent_id: nil, name: "home regions")
Category.create(id: _operator_country_groups, type_id: 21, level_id: nil, parent_id: nil, name: "operator country groups")
Category.create(id: _main_operator_by_country, type_id: 21, level_id: nil, parent_id: nil, name: "main operator by country")
Category.create(id: _operator_region_groups, type_id: 21, level_id: nil, parent_id: nil, name: "operator country region groups")
Category.create(id: _operator_partner_groups, type_id: 21, level_id: nil, parent_id: nil, name: "operator's partner groups")

Category.create(id: 200, type_id: 22, level_id: nil, parent_id: nil, name: "В своем регионе")#"in own regions")
Category.create(id: 201, type_id: 22, level_id: nil, parent_id: 200, name: "Много говорю по телефону")#"active user of calls")
Category.create(id: 202, type_id: 22, level_id: nil, parent_id: 200, name: "Отправляю много смс")#"active user of sms")
Category.create(id: 203, type_id: 22, level_id: nil, parent_id: 200, name: "Активно использую интернет")#"active user of internet")

Category.create(id: 210, type_id: 22, level_id: nil, parent_id: nil, name: "В домашнем регионе")#"in home regions")
Category.create(id: 211, type_id: 22, level_id: nil, parent_id: 210, name: "Много говорю по телефону")#"active user of calls")
Category.create(id: 212, type_id: 22, level_id: nil, parent_id: 210, name: "Отправляю много смс")#"active user of sms")
Category.create(id: 213, type_id: 22, level_id: nil, parent_id: 210, name: "Активно использую интернет")#"active user of internet")
Category.create(id: 214, type_id: 22, level_id: nil, parent_id: 210, name: "Не использую")#"no home region activity")

Category.create(id: 220, type_id: 22, level_id: nil, parent_id: nil, name: "В России, кроме домашнего региона")#"in own country")
Category.create(id: 221, type_id: 22, level_id: nil, parent_id: 220, name: "Много говорю по телефону")#"active user of calls")
Category.create(id: 222, type_id: 22, level_id: nil, parent_id: 220, name: "Отправляю много смс")#"active user of sms")
Category.create(id: 223, type_id: 22, level_id: nil, parent_id: 220, name: "Активно использую интернет")#"active user of internet")
Category.create(id: 224, type_id: 22, level_id: nil, parent_id: 220, name: "Не использую")#"no own country activity")

Category.create(id: 230, type_id: 22, level_id: nil, parent_id: nil, name: "За границей")#"abroad")
Category.create(id: 231, type_id: 22, level_id: nil, parent_id: 230, name: "Много говорю по телефону")#"active user of calls")
Category.create(id: 232, type_id: 22, level_id: nil, parent_id: 230, name: "Отправляю много смс")#"active user of sms")
Category.create(id: 233, type_id: 22, level_id: nil, parent_id: 230, name: "Активно использую интернет")#"active user of internet")
Category.create(id: 234, type_id: 22, level_id: nil, parent_id: 230, name: "Не использую")#"no abroad activity")

Category.create(id: 240, type_id: 22, level_id: nil, parent_id: nil, name: "Общая")#"general")
Category.create(id: 241, type_id: 22, level_id: nil, parent_id: 240, name: "Не выезжаю за пределы своего региона")#"home sitter")
Category.create(id: 242, type_id: 22, level_id: nil, parent_id: 240, name: "Не выезжаю за пределы домашнего региона")#"home and home region sitter")
Category.create(id: 243, type_id: 22, level_id: nil, parent_id: 240, name: "Часто путешествую по России")#"active Russia traveller")
Category.create(id: 244, type_id: 22, level_id: nil, parent_id: 240, name: "Часто выезжаю за границу")#"active foreign country traveller")

Category.create(id: 300, type_id: 23, level_id: nil, parent_id: nil, name: "general priority")
Category.create(id: 301, type_id: 23, level_id: nil, parent_id: nil, name: "individual priority")
Category.create(id: 302, type_id: 23, level_id: nil, parent_id: nil, name: "dependent is required for main")
Category.create(id: 303, type_id: 23, level_id: nil, parent_id: nil, name: "main is incompatible with dependent")

Category.create(id: 310, type_id: 24, level_id: nil, parent_id: nil, name: "main has higher priority")
Category.create(id: 311, type_id: 24, level_id: nil, parent_id: nil, name: "main has lower priority")

Category.create(id: 320, type_id: 25, level_id: nil, parent_id: nil, name: "tarif_option")
Category.create(id: 321, type_id: 25, level_id: nil, parent_id: nil, name: "tarif_without_limits")
Category.create(id: 322, type_id: 25, level_id: nil, parent_id: nil, name: "tarif_with_limits")
Category.create(id: 323, type_id: 25, level_id: nil, parent_id: nil, name: "tarif_option_with_limits")
Category.create(id: 324, type_id: 25, level_id: nil, parent_id: nil, name: "common_service")

Category.create(id: 330, type_id: 26, level_id: nil, parent_id: nil, name: "calls")
Category.create(id: 331, type_id: 26, level_id: nil, parent_id: nil, name: "sms")
Category.create(id: 332, type_id: 26, level_id: nil, parent_id: nil, name: "mms")
Category.create(id: 333, type_id: 26, level_id: nil, parent_id: nil, name: "internet")

Category.create(id: 340, type_id: 28, level_id: nil, parent_id: nil, name: "Сообщение об ошибке на сайте")
Category.create(id: 341, type_id: 28, level_id: nil, parent_id: nil, name: "Информационный запрос")
Category.create(id: 342, type_id: 28, level_id: nil, parent_id: nil, name: "Предложение об улучшении предоставляемых услуг")
Category.create(id: 343, type_id: 28, level_id: nil, parent_id: nil, name: "Предложение о сотрудничестве")
Category.create(id: 344, type_id: 28, level_id: nil, parent_id: nil, name: "Жалоба")

Category.create(id: 350, type_id: 29, level_id: nil, parent_id: nil, name: "Получено от пользователя")
Category.create(id: 351, type_id: 29, level_id: nil, parent_id: nil, name: "В работе")
Category.create(id: 352, type_id: 29, level_id: nil, parent_id: nil, name: "Обработано")

Category.create(id: Category::Operator::Const::Russian_operators, type_id: 2, level_id: nil, parent_id: nil, name: "Russian operators")
Category.create(id: Category::Operator::Const::Foreign_operators, type_id: 2, level_id: nil, parent_id: nil, name: "Foreign operators")
Category.create(id: 1020, type_id: 2, level_id: nil, parent_id: Category::Operator::Const::Russian_operators, name: "Djuice")
Category.create(id: 1021, type_id: 2, level_id: nil, parent_id: Category::Operator::Const::Russian_operators, name: "life:)")
Category.create(id: 1022, type_id: 2, level_id: nil, parent_id: Category::Operator::Const::Russian_operators, name: "PEOPLEnet")
Category.create(id: Category::Operator::Const::Tele2, type_id: 2, level_id: nil, parent_id: Category::Operator::Const::Russian_operators, name: "TELE2")
Category.create(id: 1024, type_id: 2, level_id: nil, parent_id: Category::Operator::Const::Russian_operators, name: "Utel")
Category.create(id: Category::Operator::Const::Beeline, type_id: 2, level_id: nil, parent_id: Category::Operator::Const::Russian_operators, name: "Билайн")
Category.create(id: 1026, type_id: 2, level_id: nil, parent_id: Category::Operator::Const::Russian_operators, name: "Енисейтелеком")
Category.create(id: Category::Operator::Const::KievStar, type_id: 2, level_id: nil, parent_id: Category::Operator::Const::Russian_operators, name: "КиевСтар")
Category.create(id: Category::Operator::Const::Megafon, type_id: 2, level_id: nil, parent_id: Category::Operator::Const::Russian_operators, name: "Мегафон")
Category.create(id: 1029, type_id: 2, level_id: nil, parent_id: Category::Operator::Const::Russian_operators, name: "Мотив")
Category.create(id: Category::Operator::Const::Mts, type_id: 2, level_id: nil, parent_id: Category::Operator::Const::Russian_operators, name: "МТС")
Category.create(id: Category::Operator::Const::MtsUkrain, type_id: 2, level_id: nil, parent_id: Category::Operator::Const::Foreign_operators, name: "МТС-Украина")
Category.create(id: 1032, type_id: 2, level_id: nil, parent_id: Category::Operator::Const::Russian_operators, name: "Скайлинк")
Category.create(id: 1033, type_id: 2, level_id: nil, parent_id: Category::Operator::Const::Russian_operators, name: "СМАРТС")
Category.create(id: Category::Operator::Const::FixedlineOperator, type_id: 2, level_id: nil, parent_id: Category::Operator::Const::Russian_operators, name: "Ростелеком")
Category.create(id: Category::Operator::Const::OtherRusianOperator, type_id: 2, level_id: nil, parent_id: Category::Operator::Const::Russian_operators, name: "Разный Русский оператор")
Category.create(id: 1036, type_id: 2, level_id: nil, parent_id: Category::Operator::Const::Foreign_operators, name: "Astelit")

c = Category::Region::Const
Category.create(id: c::Altaiskii_krai, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Алтайский край") #Барнаул
Category.create(id: c::Amurskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Амурская область") #Благовещенск
Category.create(id: c::Arhangelskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Архангельская область")
Category.create(id: c::Astrahanskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Астраханская область")
Category.create(id: c::Belgorodskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Белгородская область")
Category.create(id: c::Bryanskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Брянская область")
Category.create(id: c::Vladimirskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Владимирская область")
Category.create(id: c::Vologodskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Вологодская область")
Category.create(id: c::Voronezhskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Воронежская область")
Category.create(id: c::Volgogradskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Волгоградская область")
Category.create(id: c::Evreiskaya_avtonomnaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Еврейская автономная область")
Category.create(id: c::Ivanovskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Ивановская область")
Category.create(id: c::Irkutskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Иркутская область")
Category.create(id: c::Kaliningradskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Калининградская область")
Category.create(id: c::Kamchatskii_krai, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Камчатский край")
Category.create(id: c::Kaluzhskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Калужская область")
Category.create(id: c::Kemerovskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Кемеровская область")
Category.create(id: c::Kirovskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Кировская область")
Category.create(id: c::Kostromskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Костромская область")
Category.create(id: c::Krasnodarskii_krai, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Краснодарский край")
Category.create(id: c::Krasnoyarskii_krai, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Красноярский край")
Category.create(id: c::Kurganskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Курганская область")
Category.create(id: c::Kurskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Курская область")
Category.create(id: c::Leningradskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Ленинградская область")
Category.create(id: c::Lipetskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Липецкая область")
Category.create(id: c::Magadanskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Магаданская область")
Category.create(id: c::Moskovskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Московская область")
Category.create(id: c::Murmanskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Мурманская область")
Category.create(id: c::Nizhegorodskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Нижегородская область")
Category.create(id: c::Novgorodskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Новгородская область")
Category.create(id: c::Novosibirskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Новосибирская область")
Category.create(id: c::Omskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Омская область")
Category.create(id: c::Orenburgskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Оренбургская область")
Category.create(id: c::Orlovskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Орловская область")
Category.create(id: c::Penzenskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Пензенская область")
Category.create(id: c::Permskii_krai, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Пермский край")
Category.create(id: c::Primorskii_krai, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Приморский край")
Category.create(id: c::Pskovskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Псковская область")
Category.create(id: c::Respublika_adygeya, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Республика Адыгея")
Category.create(id: c::Respublika_bashkortostan, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Республика Башкортостан")
Category.create(id: c::Respublika_buryatiya, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Республика Бурятия")
Category.create(id: c::Respublika_dagestan, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Республика Дагестан")
Category.create(id: c::Respublika_saha_yakutiya, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Республика Саха (Якутия)")
Category.create(id: c::Respublika_tatarstan, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Республика Татарстан")
Category.create(id: c::Respublika_udmurtiya, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Республика Удмуртия")
Category.create(id: c::Respublika_ingushetiya, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Республика Ингушетия")
Category.create(id: c::Respublika_kabardino_balkariya, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Республика Кабардино-Балкария")
Category.create(id: c::Respublika_kalmykiya, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Республика Калмыкия")
Category.create(id: c::Respublika_karachaevo_cherkesiya, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Республика Карачаево-Черкесия")
Category.create(id: c::Respublika_kareliya, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Республика Карелия")
Category.create(id: c::Respublika_komi, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Республика Коми")
Category.create(id: c::Respublika_marii_el, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Республика Марий Эл")
Category.create(id: c::Respublika_mordoviya, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Республика Мордовия")
Category.create(id: c::Respublika_severnaya_osetiya, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Республика Северная Осетия")
Category.create(id: c::Respublika_tyva_tuva, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Республика Тыва Тува")
Category.create(id: c::Respublika_hakasiya, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Республика Хакасия")
Category.create(id: c::Rostovskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Ростовская область")
Category.create(id: c::Ryazanskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Рязанская область")
Category.create(id: c::Samarskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Самарская область")
Category.create(id: c::Saratovskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Саратовская область")
Category.create(id: c::Sahalinskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Сахалинская область")
Category.create(id: c::Sverdlovskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Свердловская область")
Category.create(id: c::Smolenskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Смоленская область")
Category.create(id: c::Stavropolskii_krai, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Ставропольский край")
Category.create(id: c::Tambovskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Тамбовская область")
Category.create(id: c::Tverskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Тверская область")
Category.create(id: c::Tomskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Томская область")
Category.create(id: c::Tulskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Тульская область")
Category.create(id: c::Tumenskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Тюменская область")
Category.create(id: c::Ulyanovskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Ульяновская область")
Category.create(id: c::Habarovskii_krai, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Хабаровский край")
Category.create(id: c::Hanty_mansiiskii_avtonomnyi_okrug, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Ханты-Мансийский автономный округ")
Category.create(id: c::Chelyabinskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Челябинская область")
Category.create(id: c::Chechenskaya_respublika, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Чеченская Республика")
Category.create(id: c::Chitinskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Читинская область")
Category.create(id: c::Chuvashskaya_respublika, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Чувашская Республика")
Category.create(id: c::Chukotskii_avtonomnyi_okrug, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Чукотский автономный округ")
Category.create(id: c::Yamalo_nenetskii_avtonomnyi_okrug, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Ямало-Ненецкий автономный округ")
Category.create(id: c::Yaroslavskaya_oblast, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Ярославская область")
Category.create(id: c::Respublika_altai, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Республика Алтай")
Category.create(id: c::Zabaikalskii_krai, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Забайкальский край")
Category.create(id: c::Respublika_krym, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Республика Крым")


Category.create(id: c::Abakan, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Абакан")
Category.create(id: c::Alaniya, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Алания")
Category.create(id: c::Anadyr, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Анадырь")
Category.create(id: c::Arhangelsk, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Архангельск")
Category.create(id: c::Astrahan, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Астрахань")
Category.create(id: c::Barnaul, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Барнаул")
Category.create(id: c::Belgorod, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Белгород")
Category.create(id: c::Birobidzhan, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Биробиджан")
Category.create(id: c::Blagoveschensk, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Благовещенск ")
Category.create(id: c::Bryansk, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Брянск")
Category.create(id: c::Velikii_novgorod, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Великий Новгород")
Category.create(id: c::Vladivostok, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Владивосток")
Category.create(id: c::Vladimir, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Владимир")
Category.create(id: c::Volgograd, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Волгоград")
Category.create(id: c::Vologda, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Вологда")
Category.create(id: c::Voronezh, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Воронеж")
Category.create(id: c::Groznyi, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Грозный")
Category.create(id: c::Ekaterinburg, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Екатеринбург")
Category.create(id: c::Ivanovo, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Иваново")
Category.create(id: c::Irkutsk, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Иркутск")
Category.create(id: c::Izhevsk, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Ижевск")
Category.create(id: c::Ioshkar_ola, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Йошкар-Ола")
Category.create(id: c::Kazan, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Казань")
Category.create(id: c::Kaliningrad, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Калининград")
Category.create(id: c::Kaluga, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Калуга")
Category.create(id: c::Kemerovo, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Кемерово")
Category.create(id: c::Kirov, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Киров")
Category.create(id: c::Kostroma, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Кострома")
Category.create(id: c::Krasnodar, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Краснодар")
Category.create(id: c::Krasnoyarsk, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Красноярск")
Category.create(id: c::Kurgan, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Курган")
Category.create(id: c::Kursk, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Курск")
Category.create(id: c::Kyzyl, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Кызыл")
Category.create(id: c::Lipetsk, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Липецк")
Category.create(id: c::Magadan, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Магадан")
Category.create(id: c::Magas, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Магас")
Category.create(id: c::Maikop, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Майкоп")
Category.create(id: c::Mahachkala, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Махачкала")
Category.create(id: c::Moskva, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Москва")
Category.create(id: c::Murmansk, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Мурманск")
Category.create(id: c::Nalchik, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Нальчик")
Category.create(id: c::Nizhnii_novgorod, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Нижний Новгород")
Category.create(id: c::Novosibirsk, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Новосибирск")
Category.create(id: c::Omsk, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Омск")
Category.create(id: c::Orenburg, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Оренбург")
Category.create(id: c::Orel, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Орел")
Category.create(id: c::Penza, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Пенза")
Category.create(id: c::Petrozavodsk, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Петрозаводск")
Category.create(id: c::Petropavlovsk_kamchatskii, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Петропавловск-Камчатский")
Category.create(id: c::Perm, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Пермь")
Category.create(id: c::Pskov, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Псков")
Category.create(id: c::Rostov, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Ростов")
Category.create(id: c::Ryazan, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Рязань")
Category.create(id: c::Salehard, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Салехард")
Category.create(id: c::Samara, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Самара")
Category.create(id: c::Sankt_peterburg, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Санкт-Петербург")
Category.create(id: c::Saransk, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Саранск")
Category.create(id: c::Saratov, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Саратов")
Category.create(id: c::Smolensk, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Смоленск")
Category.create(id: c::Mineralnye_vody, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Минеральные воды")
Category.create(id: c::Syktyvkar, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Сыктывкар")
Category.create(id: c::Tambov, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Тамбов")
Category.create(id: c::Tver, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Тверь")
Category.create(id: c::Tomsk, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Томск")
Category.create(id: c::Tula, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Тула")
Category.create(id: c::Tumen, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Тюмень")
Category.create(id: c::Ulan_ude, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Улан-Удэ")
Category.create(id: c::Ulyanovsk, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Ульяновск")
Category.create(id: c::Ufa, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Уфа")
Category.create(id: c::Habarovsk, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Хабаровск")
Category.create(id: c::Cheboksary, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Чебоксары")
Category.create(id: c::Chelyabinsk, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Челябинск")
Category.create(id: c::Cherkessk, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Черкесск")
Category.create(id: c::Chita, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Чита")
Category.create(id: c::Elista, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Элиста")
Category.create(id: c::Ugra, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Югра")
Category.create(id: c::Uzhno_sahalinsk, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Южно-Сахалинск")
Category.create(id: c::Yakutsk, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Якутск")
Category.create(id: c::Yaroslavl, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Ярославль")
Category.create(id: c::Vladikavkaz, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Владикавказ")
Category.create(id: c::Gorno_altaisk, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Горно-Алтайск")
Category.create(id: c::Stavropol, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Ставрополь")
Category.create(id: c::Sevastopol, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Russia, name: "Севастополь")


Category.create(id: c::Region_ukrainy, type_id: 0, level_id: 3, parent_id: Category::Country::Const::Ukraina, name: "регион Украины")

Category.create(id: Category::Country::Const::Mir, type_id: 0, level_id: 0, parent_id: nil, name: "World")

Category.create(id: Category::Country::Const::Evropa, type_id: 0, level_id: 1, parent_id: Category::Country::Const::Mir, name: "Europe")
Category.create(id: Category::Country::Const::Asia, type_id: 0, level_id: 1, parent_id: Category::Country::Const::Mir, name: "Asia")
Category.create(id: Category::Country::Const::Severnaya_Amerika, type_id: 0, level_id: 1, parent_id: Category::Country::Const::Mir, name: "Noth America")
Category.create(id: Category::Country::Const::Ugnaya_Amerika, type_id: 0, level_id: 1, parent_id: Category::Country::Const::Mir, name: "South America")
Category.create(id: Category::Country::Const::Afrika, type_id: 0, level_id: 1, parent_id: Category::Country::Const::Mir, name: "Africa")
Category.create(id: Category::Country::Const::Avstraliyski_kontinent, type_id: 0, level_id: 1, parent_id: Category::Country::Const::Mir, name: "Australia")

ctr = []
ctr << {:id => Category::Country::Const::Ukraina, :type_id => 0, :level_id => 2, :parent_id => Category::Country::Const::Evropa, :name => "Украина"}
ctr << {:id => Category::Country::Const::Russia, :type_id => 0, :level_id => 2, :parent_id => Category::Country::Const::Evropa, :name => "Россия"}

c = Category::Country::Const
c::All_country_list_in_array_with_russian_names.each do |country_array|
  parent_id = case
  when c::Europe_countries.include?(country_array[0]); c::Evropa;
  when c::Asia_countries.include?(country_array[0]); c::Asia;
  when c::Noth_america_countries.include?(country_array[0]); c::Severnaya_Amerika;
  when c::South_america_countries.include?(country_array[0]); c::Ugnaya_Amerika;
  when c::Africa_countries.include?(country_array[0]); c::Afrika;
  when c::Australia_countries.include?(country_array[0]); c::Avstraliyski_kontinent;
  else 
    raise(StandardError, "country is not defined: #{country_array}")
  end

  ctr << {:id => country_array[0], :type_id => 0, :level_id => 2, :parent_id => parent_id, :name => country_array[1]}
end

ActiveRecord::Base.transaction do
  Category.create(ctr)
end



#raise(StandardError, [Category.find(_operator_austria).name])#.join("\n"))

