# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb50edfeac335b0528fcd9487a966d5592535d22f49d8bcbe959048944abd202035a5986170e5d7bcc712f96d88d4675d80ba5d6a0c1cb1c0ccf38e90c872234

test:
  secret_key_base: 1c990d927db5b178f97a743c9e9f0803027f098f49275aed2411e823470fd23a28c5806634d0ad11bb7499fb958c813d517117c4c4f0eb46b9f05dd807e1db3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

